number_of_sliders: 5

slider_mapping:
#case INsensitive
#in
  - spotify|out
  - chrome|out
  - discord|out
  #out
  #TODO
  #- discord|in
  - other|in
  - other|out
  #other|in/out
  #main|in/out
  #whole name of speakers
  