number_of_sliders: 7
baud: 115200
invert: True
slider_mapping:
#case INsensitive
  - -|spotify|out
  - chrome|out
  - discord|out
  - discord|in
  - other|out
  - other|in
  - teams|in
insensitiveIN:
  - obs
  - python3.9
insensitiveOUT: [] #array