number_of_sliders: 7
invert: rue
slider_mapping:
#case INsensitive
#in
#-
  - -|spotify|out
  - chrome|out
  - discord|out
  - other|out
  #out
  - discord|in
  - teams|in
  - other|in
  #TODO
  #grupowanie
  #main|in/out
  #whole name of speakers
